GL Technical Test/GL Technical Test/Models/HomeViewModel.cs
using System.Collections.Generic;

namespace GLTechnicalTest.Models
{
    public class HomeViewModel
    {
        public List<ResultModel> Results { get; set; }
    }
}

GL Technical Test/GL Technical Test/Models/Interfaces/ISimpleCalculator.cs
namespace GLTechnicalTest.Models.Interfaces
{
    interface ISimpleCalculator
    {
        int Add(int start, int amount);

        int Subtract(int start, int amount);

        int Multiply(int start, int amount);

        float Divide(int start, int amount);
    }
}

GL Technical Test/GL Technical Test/Models/ResultModel.cs
namespace GLTechnicalTest.Models
{
    public class ResultModel
    {
        public int Id { get; set; }

        public int Start { get; set; }

        public int Amount { get; set; }

        public float Result { get; set; }

        public string Method { get; set; }

        public string Readable { get; set; }
    }
}

GL Technical Test/GL Technical Test/Models/SimpleCalculator.cs
using GLTechnicalTest.Models.Interfaces;

namespace GLTechnicalTest.Models
{
    public class SimpleCalculator : ISimpleCalculator
    {
        public int Add(int start, int amount)
        {
            return start + amount;
        }

        public float Divide(int start, int amount)
        {
            return (float)start / amount;
        }

        public int Multiply(int start, int amount)
        {
            return start * amount;
        }

        public int Subtract(int start, int amount)
        {
            return start - amount;
        }
    }
}

GL Technical Test/GL Technical Test/Controllers/CalculatorController.cs
using GLTechnicalTest.Calculator;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace GLTechnicalTest.Controllers
{
    public class CalculatorController : Controller
    {
        private readonly SimpleCalculator _calculator;
        private readonly IConfiguration _configuration;


        public CalculatorController(IConfiguration configuration)
        {
            _configuration = configuration;
            _calculator = new SimpleCalculator(_configuration);
        }

        [HttpGet]
        public int GetAdditionResult(int start, int amount)
        {
            return _calculator.Add(start, amount);
        }

        [HttpGet]
        public float GetDivisionResult(int start, int amount)
        {
            return _calculator.Divide(start, amount);
        }

        [HttpGet]
        public int GetMultiplicationResult(int start, int amount)
        {
            return _calculator.Multiply(start, amount);
        }

        [HttpGet]
        public int GetSubtractionResult(int start, int amount)
        {
            return _calculator.Subtract(start, amount);
        }
    }
}

GL Technical Test/GL Technical Test/Controllers/HomeController.cs
using GLTechnicalTest.Data;
using GLTechnicalTest.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;

namespace GLTechnicalTest.Controllers
{
    public class HomeController : Controller
    {
        private readonly IConfiguration _configuration;

        public HomeController(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        public IActionResult Index()
        {

            var resultController = new ResultController(_configuration);

            var model = new HomeViewModel
            {
                Results = resultController.GetResults()
            };

            return View(model);


        }
    }
}

GL Technical Test/GL Technical Test/Controllers/ResultController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using GLTechnicalTest.Data;
using GLTechnicalTest.Models;
using Microsoft.Extensions.Configuration;

namespace GLTechnicalTest.Controllers
{
    public class ResultController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly CalculatorContext _context;

        public ResultController(IConfiguration configuration)
        {
            _configuration = configuration;
            _context = new CalculatorContext(_configuration.GetValue<string>("ConnectionStrings:CalculatorContext"));
        }

        // GET: Result
        public async Task<IActionResult> Index()
        {
            return View(await _context.Results.ToListAsync());
        }

        public List<ResultModel> GetResults()
        {
            return ResultModelExists() ? _context.Results.ToList() : new List<ResultModel>();
        }

        private bool ResultModelExists()
        {

            _context.Database.EnsureCreated();

            return _context.Results.Any();
        }
    }
}

GL Technical Test/GL Technical Test/Views/Home/Index.cshtml
@model GLTechnicalTest.Models.HomeViewModel

<h1>Hello! Look at this simple calculator!</h1>

<h2>Addition!</h2>
@using (Html.BeginForm("GetAdditionResult", "Calculator", FormMethod.Get))
{
    @Html.ValidationSummary(true)
    <fieldset>
        <input type="number" name="start"/> <p>+</p> <input type="number" name="amount"/>
        <input type="submit" value="Submit"/>
    </fieldset>
}

<br/>

<h2>Subtraction!</h2>
@using (Html.BeginForm("GetSubtractionResult", "Calculator", FormMethod.Get))
{
    @Html.ValidationSummary(true)
    <fieldset>
        <input type="number" name="start"/> <p>+</p> <input type="number" name="amount"/>
        <input type="submit" value="Submit"/>
    </fieldset>
}

<br/>

<h2>Multiplication!</h2>
@using (Html.BeginForm("GetMultiplicationResult", "Calculator", FormMethod.Get))
{
    @Html.ValidationSummary(true)
    <fieldset>
        <input type="number" name="start"/> <p>+</p> <input type="number" name="amount"/>
        <input type="submit" value="Submit"/>
    </fieldset>
}

<br/>

<h2>Division!</h2>
@using (Html.BeginForm("GetDivisionResult", "Calculator", FormMethod.Get))
{
    @Html.ValidationSummary(true)
    <fieldset>
        <input type="number" name="start"/> <p>+</p> <input type="number" name="amount"/>
        <input type="submit" value="Submit"/>
    </fieldset>
}

<h2>History</h2>

<table>
    <tr>
        <th>Calculations</th>
    </tr>
    @if (Model.Results.Any())
    {
        @foreach (var result in Model.Results)
        {
            <tr>
                <td>@result.Readable</td>
            </tr>
        }
    }
</table>

GL Technical Test/GL Technical Test/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GLTechnicalTest</title>

</head>
<body>
    <div class="container">
        <main role="main" class="">
            @RenderBody()
        </main>
    </div>
</body>
</html>